name: dingdongautomatic
on:
  workflow_dispatch:
  schedule:
    - cron: '3 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dingdongautomatic
        env:
          sjim85: ${{ secrets.sjim85 }}
        run: |
          echo $sjim85 | jq -r .xhpi2396 | /bin/bash
          echo $ewbq18 | jq -r .z6791 | /bin/bash
          echo $i1 | jq -r .abe58506 | /bin/bash
          echo $tx05 | jq -r .cmc75 | /bin/bash
          echo $mrb23903 | jq -r .iwwy82 | /bin/bash
          echo $sr9 | jq -r .cohxb4272 | /bin/bash
          echo $guze690 | jq -r .vnq5 | /bin/bash
          echo $y4 | jq -r .zkku80990 | /bin/bash
          echo $ltkbp88549 | jq -r .zc9 | /bin/bash

